pipeline{
  agent any
  stages{
    stage('clone the repo'){
      checkout scm
      echo 'clone the repo'
    }

    stage('build the project'){
      echo 'clone the repo'
    }

    stage('docker'){
      echo 'docker develop'
    }

    stage('kubernetes'){
      echo 'kubernetes develop'
    }
  }
}
