apiVersion: apps/v1
kind: Deployment
metadata:
  name: p-deployment
  labels:
    app: p-deployment
spec:
  replicas: 3
  selector: 
    matchLabels: p-deployment
  template:
    metadata:
      labels: p-pod
    spec:
      containers:
        - name: p-deplyment
          image: yeswanthteja/practice-repo
          ports:
            containerPort: 8080
          
  
