apiVersion: v1
kind: Service
metadata:
  name: p-deployment-service
spec:
  selector:
    app: p-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
      
